### Get Sales
GET http://localhost:4004/odata/v4/manage-orders/GetSales

### Get Sale
GET http://localhost:4004/odata/v4/manage-orders/GetSales?$filter=email eq 'hdymocke0@wordpress.com'

### Create Sales
POST http://localhost:4004/odata/v4/manage-orders/CreateSales HTTP/1.1
Content-Type: application/json

{
    "email": "jrushworth1@cam.ac.uk",
    "firtsname": "Jen",
    "lastname": "Rushworth",
    "createon" : "2023-04-10"
}

### Update Sales
PUT http://localhost:4004/odata/v4/manage-orders/UpdateSales?$filter=email eq 'thellin2@uol.com.br' HTTP/1.1
Content-Type: application/json

{
    "firstname": "FirstName Updated",
    "lastname": "LastName Updated"
}

###Delete Sales
DELETE http://localhost:4004/odata/v4/manage-orders/DeleteSales?$filter=email eq 'jrushworth1@cam.ac.uk'


### Cancel Sales - Action
POST http://localhost:4004/odata/v4/manage-orders/cancelOrder 
Content-Type: application/json

{"clientEmail" : "thellin2@uol.com.br"}


