### Get Sales
GET http://localhost:4004/manage-order/Sales

### Get Sale
GET http://localhost:4004/manage-order/Sales('hdymocke0@wordpress.com')

### Create Sales
POST http://localhost:4004/manage-order/Sales HTTP/1.1
Content-Type: application/json

{
    "email": "jrushworth1@cam.ac.uk",
    "firstname": "Jen",
    "lastname": "Rushworth",
    "createon" : "2023-04-10"
}

### Update Sales
PUT http://localhost:4004/manage-order/Sales('thellin2@uol.com.br') HTTP/1.1
Content-Type: application/json

{
    "firstname": "FirstName Updated",
    "lastname": "LastName Updated"
}

###Delete Sales
DELETE http://localhost:4004/manage-order/Sales('thellin2@uol.com.br')



### Cancel Sales - Action
POST http://localhost:4004/manage-order/cancelOrder 
Content-Type: application/json

{"clientEmail" : "gsimison3@123-reg.co.uk"}


